baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Bio+Med+Vis'

google_analytics_id: ""
homepage:
  show_call_box: false
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: '© Bio+Med+Vis Platform'

seo:
  meta_og_title: "Bio+Med+Vis"
  meta_og_type: "website"
  meta_og_url: ""
  meta_og_image: ""
  meta_og_description: ""
  meta_twitter_card: ""
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  announcements:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
